spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: pagos
            uri: http://localhost:8090
            predicates:
              - Path=/api/pagos/**

  config:
    import: 'optional:configserver:http://localhost:8888'

server:
  port: 8080
